version: "3.6"
services:
  canary-postgres:
    image: postgres
    hostname: canary-postgres
    restart: unless-stopped
    container_name: canary-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER-postgres}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    depends_on:
      - canary-postgres
    ports:
      - 4000:4000
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-canary_db}
      - POSTGRES_HOST=${POSTGRES_HOST:-canary-postgres}
      ## please consult the docs for details
      - EMAIL_SITE_ADDRESS=${EMAIL_SITE_ADDRESS}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - GUARDIAN_SECRET_KEY=${GUARDIAN_SECRET_KEY}
      ## Exchanges exposure settings
      - EXCHANGES_STATS_INTERVAL=${EXCHANGES_STATS_INTERVAL:-30}
      - EXCHANGES_ALERTS_INTERVAL=${EXCHANGES_ALERTS_INTERVAL:-7}
      - EXCHANGES_HAS_TXS_INTERVAL=${EXCHANGES_HAS_TXS_INTERVAL:-7}
      - EXCHANGES_SUSPICIOUS_DEPOSIT_THRESHOLD=${EXCHANGES_SUSPICIOUS_DEPOSIT_THRESHOLD:-500000}
      - EXCHANGES_IQR_USE_POSITIVE_EXPOSURE_ONLY=${EXCHANGES_IQR_USE_POSITIVE_EXPOSURE_ONLY:-true}
      - EXCHANGES_IQR_LOWER_BOUNDARY_MULTILPLIER=${EXCHANGES_IQR_LOWER_BOUNDARY_MULTILPLIER:-1.5}
      - EXCHANGES_IQR_UPPER_BOUNDARY_MULTILPLIER=${EXCHANGES_IQR_UPPER_BOUNDARY_MULTILPLIER:-3}
      ## Mailgun settings
      - EMAIL_API_KEY=${EMAIL_API_KEY}
      - EMAIL_API_DOMAIN=${EMAIL_API_DOMAIN}
    restart: unless-stopped

  caddy:
    image: caddy:2.3.0
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy-data:/data/caddy"
      - "caddy-config:/config/caddy"
    ports:
      - ${HTTP_PORT:-8080}:80
      - ${HTTPS_PORT:-8081}:443
    environment:
        SITE_ADDRESS: ${SITE_ADDRESS:-localhost:80}
        APP_ADDRESS: ${APP_ADDRESS:-app:4000}
    restart: unless-stopped
    depends_on:
      - app

volumes:
  caddy-data:
  caddy-config:
